require('dotenv').config();

module.exports = {
  SUPPRESS_NO_CONFIG_WARNING: process.env.SUPPRESS_NO_CONFIG_WARNING,
  PORT: process.env.PORT,
  DATABASE_CONNECTION: process.env.DATABASE_CONNECTION,
  JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
  X4_SECRET_KEY: process.env.X4_SECRET_KEY,
  CLOUDINARY_NAME: process.env.CLOUDINARY_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  CLOUDINARY_ENVIRONMENT_VARIABLE: process.env.CLOUDINARY_ENVIRONMENT_VARIABLE
};
